export const a = [
  {
    id: 1,
    // img: "./original.webp",
    name: "Dr.Asarwal Kitnyassasa",
    speacilist: "speacilist",
    rating: 5.3,
    Date: 5,
  },
  {
    id: 2,
    // img: "./original.webp",
    name: "Test2",
    speacilist: "speacilist",
    rating: 5.1,
    Date: 6,
  },
  {
    id: 3,
    // img: "./original.webp",
    name: "Test3",
    speacilist: "speacilist",
    rating: 3.2,
    Date: 15,
  },
  {
    id: 4,
    // img: "./original.webp",
    name: "Test4",
    speacilist: "speacilist",
    rating: 2.2,
    Date: 10,
  },
  {
    id: 5,
    // img: "./original.webp",
    name: "Test5",
    speacilist: "speacilist",
    rating: 4.5,
    Date: 7,
  },
];
